// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1fadaffd-b4fe-4fcb-8b94-0e394c475b0c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kD52Mb2vY",
    "aws_user_pools_web_client_id": "76qp27frdc0sq89679ihl047q6",
    "oauth": {
        "domain": "intelipets-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8081/",
        "redirectSignOut": "http://localhost:8081/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "api",
            "endpoint": "https://6b57jjnjhg.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
